-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."event_match_games" add column "losing_team_id" uuid
--  not null;
