-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."events" add column "is_register_off_platform" boolean
--  not null default 'false';
