-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."venue_images" add column "is_scraped" boolean
--  not null default 'false';
