-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."play_sessions" add column "skill_rating_minimum" numeric
--  null;
