-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."event_group_sequences" add column "competition_format" text
--  not null;
