-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."venue_images" add column "host" text
--  not null default 'https://files.bounceassets.com';
