-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."event_matches" add column "is_bye" boolean
--  not null default 'false';
