-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."lesson_templates" add column "sport" text
--  not null default 'TENNIS';
