CREATE OR REPLACE VIEW "public"."user_profiles" AS 
 SELECT users.id,
    users.created_at,
    users.updated_at,
    users.deleted_at,
    users.username,
    users.coach_status,
    users.full_name,
    users.preferred_name,
    users.gender,
    users.gender_preference,
    users.about_me,
    users.about_me_video_url,
    users.coach_experience_years,
    users.coach_experience_set_at,
    users.country_subdivision_id,
    users.country_id,
    users.city_name,
    users.tennis_rating_scale_id,
    users.tennis_rating,
    users.normalized_tennis_rating_scale_id,
    users.normalized_tennis_rating,
    users.profile_image_file_name,
    users.profile_image_path,
    users.profile_image_provider,
    users.profile_image_provider_url,
    users.cover_image_file_name,
    users.cover_image_path,
    users.cover_image_provider,
    users.cover_image_provider_url,
    users.default_sport,
    users.tennis_skill_level_id,
    users.pickleball_skill_level_id,
    users.active_city_id,
    users.dupr_id,
    users.event_organizer_account_type
   FROM users;
