-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- INSERT INTO event_organizer_account_types (value)
-- VALUES
--     ('INACTIVE'),
--     ('CLUB'),
--     ('INDIVIDUAL'),
--     ('TOUR'),
--     ('OTHER');
