import { Tournament } from 'constants/tournaments';

export const baseTournamentToModel = (tournament: Record<string, any>): Tournament => {
  return {
    title: tournament.Title,
    detailsEvents: tournament['Events (from Tournament_ID)'],
    lat: +tournament.Lat[0],
    long: +tournament.Long[0],
    id: tournament.ID,
    airtableId: tournament.id,
    startDate: tournament['Start Date'],
    endDate: tournament['End Date'],
    slug: tournament.Slug,
    group: tournament['Group (Gender)'],
    region: tournament['Region'],
    season: tournament['Season'],
    division: tournament['Division'],
    tournamentDetailsId: tournament['Tournament Details'][0],
    format: tournament['Format'],
    facilityName: tournament['Name (from Facilities/Courts)'][0],
    city: tournament['City (from Facilities/Courts_ID)'][0],
    playAreaType: tournament['Play Area Type'],
    netType: tournament['Net Type'],
    surfaceType: tournament['Surface Type'],
    ball: tournament['Ball'],
    courtsNumber: tournament['# of Courts'],
    registrationCloses: tournament['Registration Closes'][0],
    registrationFee: tournament['Registration Fee'],
    events: tournament.Events,
    firstPlacePrize: tournament['First Place Prize'],
    finalistPrize: tournament['Finalist Prize'],
    venueAddress: tournament['Venue Address'],
    venueName: tournament['Venue Name'],
    description: tournament['Description'],
    ogImageUrl: tournament['ogImageUrl'],
    appImageUrl: tournament['appImageUrl'],
    sponsorImageUrl: tournament['sponsorImageUrl'],
    membersCount: tournament['Members count'],
    maxTeams: tournament['Max Teams'],
    maxTeamsPerPool: tournament['Max teams per pool'],
    filledTeamsPerGroup: tournament['Filled Teams per group'],
    brevoListId: tournament['brevoListId (from Tournament Details)'][0],
    participantsDescription: tournament['Participants Description'],
    countdownDescription: tournament['Countdown Description'],
    formatDetails: tournament['Format Details'][0],
    faq: tournament['FAQ'] ? JSON.parse(tournament['FAQ']) : [],
  };
};
