-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."event_group_registrations" add column "invited_partner_email" text
--  null;
