-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- -- For the 'countries' table
-- ALTER TABLE countries
-- DROP COLUMN IF EXISTS location;
--
-- -- For the 'country_subdivisions' table
-- ALTER TABLE country_subdivisions
-- DROP COLUMN IF EXISTS location;
--
-- -- For the 'cities' table
-- ALTER TABLE cities
-- DROP COLUMN IF EXISTS location;
--
-- -- For the 'venues' table
-- ALTER TABLE venues
-- DROP COLUMN IF EXISTS location;
