ALTER TABLE countries ADD COLUMN location GEOMETRY(POINT, 4326);
ALTER TABLE country_subdivisions ADD COLUMN location GEOMETRY(POINT, 4326);
ALTER TABLE cities ADD COLUMN location GEOMETRY(POINT, 4326);
ALTER TABLE venues ADD COLUMN location GEOMETRY(POINT, 4326);
