-- Could not auto-generate a down migration.
-- Please write an appropriate down migration for the SQL below:
-- alter table "public"."user_notification_entities" add column "group_thread_id" uuid
--  null;
